# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
os:
  - linux
  - osx
after_success:
  - Rscript -e 'covr::codecov()'
notifications:
  email: false
  slack:
    rooms:
      - secure: cs76NmF59erc2vM08f8SrffBsz7dH0sABZy0ZXpLO+lU+goDGTkdqu65DffKKo31IuUgFRLOh3uxxwgp2Vf+SMum31rtG5c666H2/XHWFlDE7oPgVozdp4FkzCbKJgKrjFPUwDaPzWJU5XfnwUwkGHMsC4v45kjDvqPYW9CpqEHV5yni+bSZkdHdehJhcEZ3NJcwowcUH34rtjiWBkZyWqNaZzGt7ShP7lBrbemiXCYyW/Jd1uCCFGRuc56zjgPQvPXou1RSnnB0A1XpCN/fgzKMxPtU/nhS9n0Jbk3U1AFsGnzW13ay6UqI2bCnmZUJx9pah5PGsqoKdpREedJHhL04QLQDPrd6FDHWrAbB0nTjJigIhrEF6tjZu2C8YN+DMWzwe+G/GbRMWypI2mWzbv086V68J0WfNnjwFis99iRKYdirRanz9CurLi1llKdEvp6gNZt0Wq3sGcxYpZmzXGSiUG34YZKt8XicFTOQrtUO27K1OkHUax5hvNj7Jez3/3++4YBIugWtzUHfEp7INFzh4dbvF3YoQGEfx6L1aXZY2m5/yuOrSsoCsEfc/sTOH3ALp7rQ18sJzEaLBjUVPW499Ws8D3YIEbhuitvpiG0TwTFg29qxDLdzJ4+izwMxuAgnq84EQOjdylv6qANEeG4Ti5Bp6s381aiJp0P6SJA=
    on_success: change # send a notification when the build status changes
    on_failure: always # always send a notification
